
builds:
- id: drop
  dir: .
  main: .
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - latest
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
